version: "3"
services:
  address-postgres:
    container_name: address-postgres
    image: postgres:11
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=addresses
    networks:
      - app-network
  address-api:
    container_name: address-api
    build: ./
    restart: unless-stopped
    ports:
      - "8001:8001"
    depends_on:
      - address-postgres
    networks:
      - app-network
networks:
  app-network:
    external:
      name: rpi

