version: "3"
services:
  user-postgres:
    container_name: user-postgres
    image: postgres:11
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=users
    networks:
      - app-network
  user-api:
    container_name: user-api
    build: ./
    restart: unless-stopped
    ports:
      - "8000:8000"
    depends_on:
      - user-postgres
    networks:
      - app-network
networks:
  app-network:
    external:
      name: rpi

